### ISSUE TITLE
Prepare Final Demo Draft

### ISSUE THREAD

**Issue by kmaslowiec** [intive/patronage22-android-szczecin#115]
Write a pseudo script for the demonstration that includes:

- Subjects that we want to include in the introduction
- Screens that we want to present and the scenarios 
- Media type: Google Slides?

**Please add the suggestions in the comments.**

**Comment by kmaslowiec** [comment]
@catchanus @Nataniel-Antosik 
During the draft we can present the following scenarios:

**Success Response:**

- Login with an e-mail to the app
- Add boards / Delete?
- Add cards / Delete?
- Edit card and boards if possible
- Offline response
- Board Details.

**Error responses:**
On Boards, Boards details, Cards

The last page/slide: About us

Suggested type of the file: Google Slide

**Comment by Nataniel-Antosik** [comment]
Maybe  before login we can show all possible scenarios with Firebase. Registration login and login if we have account. After add board we add some cards and wait to refresh. And maybe on the end we can show screen with licenses. And I know it is only template and we will talk about details.
